
name="shuttr-speed"
main="./.svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-03-10"
account_id = "d7c0f78c25d131d8575cbe63df040d39"

site.bucket = "./.svelte-kit/cloudflare"

build.command = "npm run build"
